server:
  port: 9111
  servlet.context-path: /ch-vacd-api-reference-server
  forward-headers-strategy: framework

spring:
  application.name: ch-vacd-API-reference-server

# H2 in-memory datasource (for development)
  datasource:
    url: jdbc:h2:mem:vacd;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driverClassName: org.h2.Driver

# JPA
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate.ddl-auto: update

# HAPI FHIR server servlet mapping
hapi:
  fhir:
    server:
      path: /fhir/*
      server_validation_flag_fail_on_severity: error
    pretty_print: true
    default_response_encoding: json
    openapi_enabled: true
    validation:
      request_enabled: true
      allow_local_references: true

# define which resource providers to load (comma-separated list). empty list means "load all"
fhir:
  providers: BundleProvider, ImmunizationProvider, OrganizationProvider, PatientProvider, PractitionerProvider, PractitionerRoleProvider, RelatedPersonProvider, ValueSetProvider
  ig:
    files: >
      classpath:/packages/ch.fhir.ig.ch-core#7.0.0-ballot.tgz,
      classpath:/packages/ch.fhir.ig.ch-term#3.4.0.tgz,
      classpath:/packages/ch.fhir.ig.ch-vacd#7.0.0-ballot.tgz

# EHRbase CDR connection
ehrbase:
  url: ${CDR_URL:http://ehrbase:8080/ehrbase/rest/openehr/v1}
  user: ${CDR_USER:ehrbase-user}
  password: ${CDR_PASS:SuperSecretPassword}

# openFHIR mapping engine
openfhir:
  url: ${MAPPER_URL:http://openfhir:8083}
  template-id: ${OPENFHIR_TEMPLATE_ID:ch-vacd-immunization-administration.v1-alpha}

logging:
  level:
    root: INFO
    org.hibernate: WARN
    fhir.log: DEBUG
