spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/vacd_audit_trace
    username: vacduser
    password: vacduser
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

