spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/chvacdapirefserver
    username: vacduser
    password: vacduser
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

ehrbase:
  url: http://localhost:8082/ehrbase/rest/openehr/v1

#openFHIR mapping engine
openfhir:
  url: http://localhost:8083

app:
  bootstrap:
    enabled: false